import os
import re
import random
import google.generativeai as genai
from datetime import datetime

# Configure Gemini
genai.configure(api_key=os.environ["GOOGLE_GENERATIVE_AI_API_KEY"])

QUOTE_STYLES = [
    "motivational and uplifting",
    "funny and humorous",
    "witty and sarcastic",
    "deterministic and stoic",
    "philosophical and thought-provoking",
    "nerdy and programming-related",
    "self-deprecating developer humor",
    "inspirational about life and growth",
]

def get_quote():
    style = random.choice(QUOTE_STYLES)
    today = datetime.now().strftime("%A, %B %d %Y")

    prompt = f"""Generate a single unique quote for today ({today}) that is {style}.
    
Rules:
- The quote must be original and not a famous existing quote
- Keep it under 25 words
- Make it memorable and thoughtful
- Return ONLY the quote text with NO attribution, NO author, NO extra text, NO quotation marks
- Just the raw quote sentence itself"""

    model = genai.GenerativeModel("gemini-2.0-flash")
    response = model.generate_content(prompt)
    quote = response.text.strip().strip('"').strip("'").strip()
    return quote, style

def update_readme(quote, style):
    readme_path = "README.md"

    with open(readme_path, "r", encoding="utf-8") as f:
        content = f.read()

    today = datetime.now().strftime("%B %d, %Y")
    style_emoji = {
        "motivational and uplifting": "🚀",
        "funny and humorous": "😂",
        "witty and sarcastic": "😏",
        "deterministic and stoic": "🧱",
        "philosophical and thought-provoking": "🤔",
        "nerdy and programming-related": "💻",
        "self-deprecating developer humor": "🙃",
        "inspirational about life and growth": "🌱",
    }
    emoji = style_emoji.get(style, "✨")

    quote_block = f"""
<div align="center">

> {emoji} *"{quote}"*

<sub>🗓️ {today} &nbsp;|&nbsp; 🤖 Generated by Gemini AI</sub>

</div>
"""

    # Replace between markers
    pattern = r"(<!--STARTS_HERE_QUOTE_README-->)(.*?)(<!--ENDS_HERE_QUOTE_README-->)"
    replacement = f"<!--STARTS_HERE_QUOTE_README-->{quote_block}<!--ENDS_HERE_QUOTE_README-->"

    new_content = re.sub(pattern, replacement, content, flags=re.DOTALL)

    if new_content == content:
        print("⚠️  Markers not found! Check README.md for <!--STARTS_HERE_QUOTE_README--> and <!--ENDS_HERE_QUOTE_README-->")
    else:
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(new_content)
        print(f"✅ README updated successfully!")
        print(f"   Style: {style}")
        print(f"   Quote: {quote}")

if __name__ == "__main__":
    print("🤖 Fetching today's quote from Gemini AI...")
    quote, style = get_quote()
    update_readme(quote, style)
