name: Update Quote

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate Daily Quote
        uses: ruchernchong/quotely@4fa41f13b2515ae2b9bddd128a89fd666231be2e
        with:
          google-generative-ai-api-key: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}
          auto-commit: true
